# 刷流配置
[brush]
# 保留最小剩余磁盘空间，单位 B，默认1024GiB即1024 * 1024 * 1024 * 1024，剩余空间小于此值不会再添加新的任务
min_disk_space = 1099511627776

# 位于下载状态的种子数上限，当qb中下载状态种子数大于此值时不会添加新的任务
max_downloading_torrents = 6  

# 平均速度计算用的时间周期，默认即可，不推荐修改
upload_cycle = 600  # 平均上传速度计算周期，单位秒，默认600秒即10分钟 
download_cycle = 600 # 平均下载速度计算周期，单位秒，默认600秒即10分钟

# 期望达到的整体上传速度，单位 B/s， 推荐设置为上传速率的50%，比如:30M上行速率，推荐设置为 (15/8) * 1024 * 1024 = 1966080
# 一个时间周期内的平均上传速度大于此值的情况下，不会添加新的任务
expect_upload_speed = 1966080  # 刷流：上传速度上限，单位 B/s，默认3932160B/s即30M上传带宽对应值(30 / 8 * 1024 * 1024)。当qb中上传速度大于此值时不会添加新的任务   

# 期望达到的整体下载速度，单位 B/s，默认值: 13,107,200 B/s 即 100M下行速率对应的值
# 一个时间周期内的最大下载速度大于此值的情况下，不会添加新的任务
# 为什么要有这个逻辑， 因为我发现QB中如果有正在下载的任务且下载速度较快达到了10MiB/s，那么其他正在上传的种子会受到影响上传速度会降低很多。
# 当但下载任务完成时或下载速度放慢时，其他正在上传的种子会恢复正常上传速度。
# 因此，当下载速度达到一定值时，不再添加新的任务，避免下载任务过多导致上传速度降低。直到下载速度降低后一段时间，上传速度还没有达标再进行添加新的任务。
expect_download_speed = 13107200


# 下载器设置，仅支持qb
[downloader]
url = "http://127.0.0.1:8080"
username = ""
password = ""

# M-Team配置示例，请自行替换x-api-key参数
[[sites]]
name = "M-Team"

[sites.options]
free_only = false

[[sites.headers]]
key = "x-api-key"
value = "xxxxx"
